### ISSUE TITLE
RFeature onClick doesn't work inside RLayerCluster

### ISSUE THREAD

**Issue by macaframaretard** [mmomtchev/rlayers#143] opened 2023-03-22 11:21 UTC
RFeature onClick doesn't work inside RLayerCluster

**Example**
```
  <RLayerCluster
          distance={distance}
          ref={clusterLayerRef}
          zIndex={1000}
          style={(feature, resolution) =>
            getClusterStyle(feature, resolution, featuresOriginalData)
          }
        >
          {featuresArray.map((f: Feature, index) => {
            return (
              <RFeature
                feature={f}
                key={index}
                onClick={() => console.log(index)}
              />
            );
          })}
        </RLayerCluster>
```

**Comment by mmomtchev** [comment] 2023-03-22 12:11
Yes, I confirm, currently this is not supported.

**Comment by macaframaretard** [comment] 2023-03-22 12:29
@mmomtchev so, how i can use  RPopup inside RLayerCluster?

**Comment by mmomtchev** [comment] 2023-03-22 12:41
The problem is that individual features in a cluster layer might not be visible. You will have to attach your popup to the super-feature and there are lots of special cases to handle. Is this what you want, attach your popup to the cluster?

**Comment by macaframaretard** [comment] 2023-03-22 12:54
I want to attach one type of popups to super-feature(is superfeature cluster of features?) and attach another popups to features. I've tried, but trigger doesn't work

**Comment by mmomtchev** [comment] 2023-03-22 13:22
If you attach an `onClick` handler to the cluster layer itself, it should get called when clicking on clusters. However will be passed the super-feature, not individual features.

Being able to call the `onClick` handler of individual features is probably useful and I will consider adding it.

However popups will be more difficult as these will have to be merged.

**Closed** 2023-03-28 16:04 UTC
Labels: enhancement
