### ISSUE TITLE
Support for tailwindcss?

### ISSUE THREAD

**Issue by louisguitton** [mmomtchev/rlayers#162] opened 2023-06-23 15:16 UTC
Hi, thanks for this great work.

## Description of the Error
I have tried to drop your library in my Next.js 13 App router + Tailwindcss boilerplate (for which you don't have test coverage for, so if it's not relevant or supported let me know) (you have coverage for Next.js Pages router without tailwindcss).

First, I try running a simple example without any changes to the next.js config. I get the following warning and errors:
```
- warn ./node_modules/web-worker/cjs/node.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/web-worker/cjs/node.js
./node_modules/geotiff/dist-module/worker/decoder.js
./node_modules/geotiff/dist-module/pool.js
./node_modules/geotiff/dist-module/geotiff.js
./node_modules/ol/source/GeoTIFF.js
./node_modules/ol/source.js
./node_modules/rlayers/dist/layer/RLayerTile.js
./node_modules/rlayers/dist/index.js
./src/app/page.tsx
- error node_modules/ol/Map.js (365:0) @ new Map
- error ReferenceError: document is not defined
null
```

Then, I follow your documentation, I do this:
```js
const nextConfig = { experimental: { esmExternals: "loose" } };
const withTranspile = require("next-transpile-modules")(["ol", "rlayers"]);
module.exports = withTranspile(nextConfig);
```
at which point I start getting this error and the app doesn't start:
```
- error ./src/app/globals.css
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @tailwind base;
| @tailwind components;
| @tailwind utilities;

Import trace for requested module:
./src/app/globals.css
```

## Hint
I'm guessing tailwindcss needs preprocessor that the `withTrabspile` removes.

## How to reproduce
```sh
# answer Yes to all defaults
npx create-next-app@latest
npm install rlayers ol react react-dom
npm install next-transpile-modules
npm run dev
```
change your `src/app/page.tsx` to this
```tsx
"use client";
import React from "react";
import { fromLonLat } from "ol/proj";
import "ol/ol.css";

import { RMap, ROSM } from "rlayers";

const center = fromLonLat([-1.4982172, 47.2517975]);
const zoom = 14;

export default function Home() {
  return (
    <div className="min-h-full bg-gray-100">
      <div className="py-10">
        <header>
          <div className="px-4 mx-auto max-w-7xl sm:px-6 lg:px-8">
            <h1 className="text-3xl font-bold leading-tight tracking-tight text-gray-900">
              Dashboard
            </h1>
          </div>
        </header>
        <main>
          <div className="mx-auto max-w-7xl sm:px-6 lg:px-8">
            <RMap
              initial={{ center: center, zoom: zoom }}
              className="w-full h-96">
              <ROSM />
            </RMap>
          </div>
        </main>
      </div>
    </div>
  );
}
```

**Comment by mmomtchev** [comment] 2023-06-23 16:15
I have never used tailwindcss, but I have used rlayers in projects with both Next.js 13 app mode and Next.js 13 pages mode, so this is supported.
From what I see of your output:
* The geotiff dependency on webworker comes from OpenLayers and it is not a huge problem, though you might report it to them - it is caused by a stub that is needed only when unit-testing in Node.js
* I agree that your CSS probably needs special handling - that is probably overridden by `withTranspile`. Whether you transpile `rlayers` or not is up to you - `rlayers` comes with both ESM modules and a pre-transpiled version. If you switch to using the ESM modules, there should be a way to make it work with Next.js 13 without any special configuration. Or you can try to find whatever configuration tailwindcss adds to Next.js and add it manually to the config file.

**Comment by mmomtchev** [comment] 2023-06-23 17:45
I have included a test for a setup without `withTranspile`: https://github.com/mmomtchev/rlayers-npm-tests/tree/main/next13-esm

The alias is needed because otherwise webpack will always select the CJS over the ES6 module because `rlayers` is not marked as ES6-only.

OpenLayers have decided to go ES6-only which by nw is probably the better solution, as almost no browser software uses anything else in 2023.

Maybe I will do the same in a future release.

**Closed by mmomtchev** 2023-06-23 17:45 UTC

**Comment by louisguitton** [comment] 2023-06-23 21:54
thank you sir 🙏
